<a href="https://colab.research.google.com/github/SethATU/ml-campus_data_project-colab/blob/main/miniProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machien Learning Mini Project - Seth Butler

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

In [33]:
df = pd.read_csv(
    '/content/drive/MyDrive/Colab Notebooks/CampusWalkDataset_TemplateIDs.csv',
    skiprows = 4
    )

## 1st Investigation

In [39]:
# Drop columns and rows that have NaN
cleaned_df = df.dropna(how='all', axis=0)
cleaned_df = cleaned_df.dropna(how='all', axis=1) # Columns
cleaned_df = cleaned_df.dropna(how='any', axis=0) # Rows

# Set pandas options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Display the complete cleaned table
display(cleaned_df)

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,other_sound_type_nature,insects_count,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes
5,R26_002,22/09/2026,L01 MainEntrance,Sunny,17,Moderate,Low,Traffic,Human voices,Other birds,Insects,2.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush
10,R26_003,22/09/2026,L01 MainEntrance,Sunny,18,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush
32,R26_007,22/09/2026,L04 PathFrontiHub,Sunny,17,Loud,Moderate,Traffic,Human voices,Other birds,Wind,3.0,1.0,One or two,Some,Some,Some,Neutral,Slighly uneasy,Mostly calm,No change,Wind,Ambulance
40,R26_009,22/09/2026,L01 MainEntrance,Sunny,16,Moderate,Moderate,Human voices,Traffic,Trees,Other birds,1.0,3.0,Many,Some,Many,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Barren,People smoking
41,R26_009,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,1.0,1.0,Many,Many,Some,Many,Very positive wellbeing,Easy,Very calm,Much more connected,Fallen leaves,Bags left outside library wall
42,R26_009,22/09/2026,L04 PathFrontiHub,Sunny,16,Loud,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Many,Many,Neutral,Slighly uneasy,Stressful,Less connected,More variety in planted shrubs,Loud traffic noise
43,R26_009,22/09/2026,L05 GreenFrontSportsCentre,Sunny,17,Quiet,Low,Traffic,Human voices,Wind,Trees,5.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Easy,Mostly calm,Much more connected,Little annoying bugs,Lots of dumped clothes
69,R26_015,23/09/2026,L02 LibraryGreen,Sunny,18,Moderate,Moderate,Traffic,Human voices,Other birds,Wind,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,No change,"Trees, birds, wind sound",gardai
70,R26_015,23/09/2026,L04 PathFrontiHub,Sunny,17,Loud,High,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Trees, bushes",fumes
73,R26_015,23/09/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Other,Human voices,Wind,Trees,3.0,1.0,Many,Many,Some,Many,Neutral,Easy,Mostly calm,Less connected,"Trees, birds, wind sound",machinery
75,R26_016,23/09/2026,L04 PathFrontiHub,Sunny,17,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,A little more connected,Trees and Grass,Traffic Volume highest here
81,R26_017,23/09/2026,L07 CarParkNearSportsCentre,Partly cloudy,17,Quiet,Low,Human voices,Service machinery,Wind,Other,1.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees,a telehandler
86,R26_018,23/09/2026,L07 CarParkNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Other,Wind,Trees,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Nothing worth noting,Teleporter and lots of cars (Parking lot)
87,R26_018,23/09/2026,L02 LibraryGreen,Partly cloudy,17,Moderate,High,Human voices,Traffic,Other birds,Wind,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees and Grass,Lot of people nd olice station
88,R26_018,23/09/2026,L04 PathFrontiHub,Partly cloudy,17,Moderate,Moderate,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,Trees,Traffic Volume highest here
89,R26_019,24/09/2026,L04 PathFrontiHub,Sunny,17,Moderate,High,Traffic,Human voices,Wind,Trees,7.0,6.0,Many,Some,Some,Some,Positive wellbeing,Slighly uneasy,Neutral,A little more connected,Bugs,Lots of smokers/vapers
90,R26_019,25/09/2026,L03 LowerSidePathiHub,Sunny,17,Quiet,Low,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Lots of weeds,No one around
92,R26_019,27/09/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Construction,Human voices,Wind,Trees,2.0,2.0,One or two,Some,Some,Some,Neutral,Slighly uneasy,Neutral,Much more connected,"Crabapple tree, apples sour",Lots of webs no spiders
99,R26_021,23/09/2026,L01 MainEntrance,Sunny,17,Moderate,Low,Traffic,Human voices,Wind,Trees,5.0,6.0,Many,Some,Some,Some,Neutral,Easy,Neutral,A little more connected,birds come and go,Lots of smokers/vapers
114,R26_024,23/09/2026,L05 GreenFrontSportsCentre,Windy,16C,Moderate,low,Traffic,Human voices,Wind,Trees,6.0,0.0,Many,Some,Some,Some,Low wellbeing,Slighly uneasy,Neutral,Less connected,tree,clothes were by the tree
118,R26_024,23/09/2026,L04 PathFrontiHub,Sunny,17C,Loud,Moderate,Traffic,Human voices,Wind,Other birds,2.0,3.0,Many,Some,Many,Many,Neutral,Slighly uneasy,Neutral,Less connected,The plants,Bench
126,R26_026,23/09/2026,L03 LowerSidePathiHub,Sunny,17,Moderate,Moderate,Human voices,Traffic,Wind,Trees,0.0,0.0,Many,Many,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,dried leaves,dog
132,R26_027,23/09/2026,L05 GreenFrontSportsCentre,Windy,16C,Quiet,Low,Traffic,Human voices,Other birds,Trees,3.0,0.0,Many,Some,Some,Some,Low wellbeing,Slighly uneasy,Neutral,Less connected,Trees,There are clothes left near a tree

The code above displayed a table of the data with any Row and Columb containing NaN removed.
However if a row is has 1 cell missing data the whole row is removed, whic losses valuable data.

## 2nd Investigation

In [60]:
# Drop columns and rows that have NaN
cleaned_df = df.dropna(how='all', axis=0)
cleaned_df = cleaned_df.dropna(how='all', axis=1)

# Fill all NaN cells with an empty space
cleaned_df = cleaned_df.fillna(value= " ")

# Get List of colum names and slice list for colums 2 to 23
target_cols = cleaned_df.columns[2:23]

# Check if all the cells in colums 2-23 are " "
# If it is not all " " then save it to rows_to_keep
rows_to_keep = ~(cleaned_df[target_cols] == " ").all(axis=1)

# Update the Cleaned DataFrame with only rows and colums that have data in them
cleaned_df = cleaned_df[rows_to_keep]

# Set pandas options to display all rows and columns
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns',None)
pd.set_option('display.width', None)

# Display the table
display(cleaned_df)

,recorder_id,date,location,weather,temperature_c,sound level,foot_traffic,primary_sound_type_urban,other_sound_type_urban,primary_sound_type_nature,other_sound_type_nature,insects_count,birds_count,trees_presence,native_or_wild_plant_presence,ornnamental_or_planted_plant_presence,moss_or_lichen_presence,wellbeing_rating,ease_rating,stress_rating,nature_connection_experience_rating,most_notable_nature_element,other_notes
0,R26_001,22/09/2026,L01 MainEntrance,Partly cloudy,16,Quiet,Low,Human voices,Traffic,Wind,Trees,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Stressful,Less connected,Plants and trees,
1,R26_001,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,2.0,Many,,Some,,Positive wellbeing,Neutral,Neutral,A little more connected,Sunrays on grass,
2,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Wind,Other birds,10.0,20.0,Many,,Many,Some,Positive wellbeing,Easy,Mostly calm,No change,Very quiet,
3,R26_001,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Human voices,Wind,Other birds,0.0,2.0,One or two,Some,,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Harsh wind,
4,R26_001,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Moderate,Low,Traffic,Other,Wind,Trees,0.0,0.0,One or two,,Some,,Positive wellbeing,Easy,Mostly calm,Less connected,Crowded area,
5,R26_002,22/09/2026,L01 MainEntrance,Sunny,17,Moderate,Low,Traffic,Human voices,Other birds,Insects,2.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush
6,R26_002,22/09/2026,L04 PathFrontiHub,Windy,17,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Neutral,Neutral,Very calm,No change,plants and trees,
7,R26_002,22/09/2026,L05 GreenFrontSportsCentre,Sunny,19,Moderate,Low,Traffic,Service machinery,Wind,Other,7.0,0.0,Many,Many,Many,Many,Positive wellbeing,Vey easy,Mostly calm,Much more connected,wild plants,
8,R26_002,22/09/2026,L06 HedgingBehindSportsCentre,Cloudy,16,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Very calm,Less connected,shaded area,
9,R26_002,22/09/2026,L07 CarParkNearSportsCentre,Sunny,18,Quiet,Low,Service machinery,Traffic,Other birds,Trees,6.0,2.0,Many,Many,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,insects,
10,R26_003,22/09/2026,L01 MainEntrance,Sunny,18,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,Football in Bush
11,R26_003,22/09/2026,L04 PathFrontiHub,Sunny,17,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Easy,Mostly calm,Much more connected,The Plants,
12,R26_003,22/09/2026,L05 GreenFrontSportsCentre,Sunny,18,Moderate,Moderate,Traffic,Service machinery,Wind,Insects,7.0,1.0,Many,Many,Many,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,The Wild Plants,
13,R26_003,22/09/2026,L06 HedgingBehindSportsCentre,Cloudy,16,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,
14,R26_003,22/09/2026,L07 CarParkNearSportsCentre,Sunny,18,Quiet,Low,Service machinery,Traffic,Trees,Insects,5.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Insects,
15,R26_004,22/09/2026,L04 PathFrontiHub,Sunny,17,Moderate,Low,Traffic,Other,Wind,Insects,2.0,2.0,Many,Some,Many,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Plants,
16,R26_004,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Quiet,Low,Traffic,Human voices,Wind,Trees,3.0,1.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,Less connected,Shaded area,
17,R26_004,22/09/2026,L01 MainEntrance,Sunny,17,Moderate,Low,Traffic,Human voices,Other birds,Wind,1.0,4.0,One or two,Some,Some,Many,Very positive wellbeing,Vey easy,Very calm,Much more connected,Trees,
18,R26_004,22/09/2026,L05 GreenFrontSportsCentre,Sunny,19,Moderate,Low,Traffic,Human voices,Wind,Insects,1.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Vey easy,Very calm,Much more connected,Reddish plants,
19,R26_004,22/09/2026,L02 LibraryGreen,Sunny,18,Quiet,Low,Service machinery,Traffic,Trees,Insects,5.0,2.0,Many,Some,Some,Some,Very positive wellbeing,Vey easy,Very calm,Much more connected,Insects,
20,R26_005,22/09/2026,L01 MainEntrance,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,The wind,
21,R26_005,22/09/2026,L02 LibraryGreen,Sunny,16,Quiet,Low,Traffic,Human voices,Trees,Insects,1.0,0.0,Many,Some,Many,,Very positive wellbeing,Vey easy,Very calm,Much more connected,Leaves falling,
22,R26_005,22/09/2026,L04 PathFrontiHub,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Other,0.0,3.0,Many,Some,Some,,Very low wellbeing,Very uneasy,Very stressful,No change,Faint music from car,
23,R26_005,22/09/2026,L05 GreenFrontSportsCentre,Sunny,15,Quiet,Low,Other,Human voices,Trees,Other birds,0.0,2.0,Many,Many,Many,Some,Low wellbeing,Vey easy,Mostly calm,Much more connected,Quiet,
24,R26_005,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Quiet,Low,Construction,Traffic,Seagulls,Other birds,2.0,4.0,Many,Many,Some,Some,Low wellbeing,Slighly uneasy,Mostly calm,No change,Seaguls,
25,R26_006,22/09/2026,L01 MainEntrance,Partly cloudy,16,Moderate,Moderate,Human voices,Traffic,Wind,Other birds,0.0,0.0,Many,,Some,Some,Low wellbeing,Slighly uneasy,Stressful,Less connected,Trees,
26,R26_006,22/09/2026,L02 LibraryGreen,Partly cloudy,16,Moderate,Low,Traffic,Human voices,Other birds,Wind,5.0,2.0,Many,,,,Neutral,Easy,Neutral,A little more connected,Grass,
27,R26_006,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Construction,Traffic,Other birds,Wind,2.0,12.0,One or two,,Some,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Plants,
28,R26_006,22/09/2026,L07 CarParkNearSportsCentre,Sunny,16,Quiet,Low,Construction,Traffic,Wind,Trees,0.0,1.0,One or two,Some,,Some,Very low wellbeing,Slighly uneasy,Stressful,Less connected,lawn,
29,R26_006,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Moderate,Low,Traffic,Other,Wind,Other birds,0.0,0.0,One or two,,Some,Some,Low wellbeing,Neutral,Mostly calm,No change,Tree,Generator
30,R26_007,22/09/2026,L01 MainEntrance,Partly cloudy,17,Moderate,High,Human voices,Traffic,Trees,Other birds,3.0,4.0,Many,Some,Many,Some,Neutral,Slighly uneasy,Stressful,No change,Wind,
31,R26_007,22/09/2026,L03 LowerSidePathiHub,Cloudy,16,Moderate,Low,Traffic,Human voices,Other birds,Insects,3.0,1.0,One or two,Some,,Many,Positive wellbeing,Neutral,Mostly calm,No change,,Trash
32,R26_007,22/09/2026,L04 PathFrontiHub,Sunny,17,Loud,Moderate,Traffic,Human voices,Other birds,Wind,3.0,1.0,One or two,Some,Some,Some,Neutral,Slighly uneasy,Mostly calm,No change,Wind,Ambulance
33,R26_007,22/09/2026,L06 HedgingBehindSportsCentre,Cloudy,15,Quiet,Moderate,Traffic,Construction,Trees,Other birds,31.0,12.0,Many,Some,Many,Many,Positive wellbeing,Easy,Mostly calm,No change,Snails on wall,
34,R26_007,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Quiet,Low,Traffic,Other,Wind,Other birds,4.0,1.0,One or two,Some,Some,Many,Neutral,Slighly uneasy,Neutral,No change,Tweeting Birds,
35,R26_008,22/09/2026,L01 MainEntrance,Partly cloudy,16,Moderate,Moderate,Human voices,Traffic,Wind,Wind,1.0,3.0,Many,Some,,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Sunny,
36,R26_008,22/09/2026,L03 LowerSidePathiHub,Partly cloudy,16,Moderate,Low,Traffic,Traffic,Trees,Wind,0.0,3.0,Many,Many,,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Quiet,
37,R26_008,22/09/2026,L08 AccessRoadNearSportsCentre,Partly cloudy,16,Quiet,Low,Service machinery,Traffic,Wind,Other birds,3.0,3.0,One or two,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,,
38,R26_008,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,16,Quiet,Low,Human voices,Human voices,Wind,Trees,26.0,13.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,,A soft yellow golf ball
39,R26_008,22/09/2026,L04 PathFrontiHub,Partly cloudy,16,Moderate,Moderate,Traffic,Other,Wind,Wind,1.0,3.0,Many,Some,Some,,Positive wellbeing,Easy,Mostly calm,A little more connected,,
40,R26_009,22/09/2026,L01 MainEntrance,Sunny,16,Moderate,Moderate,Human voices,Traffic,Trees,Other birds,1.0,3.0,Many,Some,Many,Some,Positive wellbeing,Neutral,Mostly calm,A little more connected,Barren,People smoking
41,R26_009,22/09/2026,L02 LibraryGreen,Sunny,16,Moderate,Low,Traffic,Human voices,Wind,Trees,1.0,1.0,Many,Many,Some,Many,Very positive wellbeing,Easy,Very calm,Much more connected,Fallen leaves,Bags left outside library wall
42,R26_009,22/09/2026,L04 PathFrontiHub,Sunny,16,Loud,Low,Traffic,Human voices,Wind,Trees,0.0,1.0,Many,Some,Many,Many,Neutral,Slighly uneasy,Stressful,Less connected,More variety in planted shrubs,Loud traffic noise
43,R26_009,22/09/2026,L05 GreenFrontSportsCentre,Sunny,17,Quiet,Low,Traffic,Human voices,Wind,Trees,5.0,0.0,Many,Many,Many,Many,Very positive wellbeing,Easy,Mostly calm,Much more connected,Little annoying bugs,Lots of dumped clothes
44,R26_009,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,15,Quiet,Low,Traffic,Construction,Trees,Seagulls,6.0,1.0,,Some,Some,Many,Neutral,Neutral,Very calm,Much more connected,Lots of bushes,Yellow Golfball
45,R26_010,22/09/2026,L01 MainEntrance,Partly cloudy,17,Moderate,Low,Human voices,Traffic,Wind,Other birds,1.0,0.0,Many,Some,,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Smoking people,
46,R26_010,22/09/2026,L02 LibraryGreen,Partly cloudy,17,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,2.0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,More birds,
47,R26_010,22/09/2026,L04 PathFrontiHub,Partly cloudy,17,Loud,Low,Traffic,Human voices,Wind,Insects,1.0,0.0,Many,Some,Many,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Spider,
48,R26_010,22/09/2026,L05 GreenFrontSportsCentre,Partly cloudy,17,Moderate,Low,Traffic,Traffic,Wind,Wind,0.0,0.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,Trafic sound,
49,R26_010,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17,Quiet,Low,Traffic,Traffic,Wind,Wind,0.0,0.0,,Some,,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,crab apple,
50,R26_011,22/09/2026,L01 MainEntrance,Partly cloudy,17,Loud,High,Human voices,Traffic,Wind,Other birds,1.0,2.0,Many,Many,,Some,Positive wellbeing,Easy,Very calm,No change,Trees,Smoking
51,R26_011,22/09/2026,L02 LibraryGreen,Partly cloudy,16,Loud,Moderate,Traffic,Human voices,Other birds,Trees,4.0,2.0,Many,Some,,Some,Positive wellbeing,Easy,Mostly calm,Less connected,Grass,
52,R26_011,22/09/2026,L03 LowerSidePathiHub,Partly cloudy,17,Quiet,Low,Human voices,Traffic,Seagulls,Wind,0.0,2.0,One or two,Some,Many,Some,Positive wellbeing,Easy,Very calm,No change,Flowerbed,
53,R26_011,22/09/2026,L05 GreenFrontSportsCentre,Partly cloudy,17,Moderate,Low,Traffic,Human voices,Trees,Wind,3.0,1.0,Many,Many,Some,,Positive wellbeing,Easy,Very calm,No change,Wildflower area,pathway
54,R26_011,22/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17,Quiet,Low,Other,Human voices,Other birds,Trees,1.0,2.0,Many,Some,Many,,Positive wellbeing,Easy,Very calm,No change,Bush,gunshots
55,R26_012,22/09/2026,L05 GreenFrontSportsCentre,Sunny,18,Moderate,Low,Traffic,Other,Other,Wind,20.0,0.0,Many,Many,,Some,Neutral,Neutral,Neutral,Less connected,some sort of a falcon,
56,R26_012,22/09/2026,L02 LibraryGreen,Sunny,17,Loud,Moderate,Traffic,Human voices,Other birds,Other birds,0.0,10.0,Many,,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Birds, Trees",Construction site
57,R26_012,22/09/2026,L06 HedgingBehindSportsCentre,Cloudy,13,Quiet,Low,Construction,Traffic,Other birds,Trees,10.0,5.0,Many,Some,,,Very positive wellbeing,Vey easy,Very calm,No change,"Trees, bushes",People
58,R26_012,22/09/2026,L01 MainEntrance,Sunny,17,Loud,High,Human voices,Traffic,Other birds,Wind,0.0,5.0,Many,,Some,Many,Very positive wellbeing,Vey easy,Mostly calm,No change,"Trees, birds, wind sound",People smoking
59,R26_013,22/09/2026,L01 MainEntrance,Sunny,16,Moderate,High,Human voices,Traffic,Wind,Trees,0.0,3.0,Many,Some,,,Positive wellbeing,Neutral,Very calm,No change,Leaves,
60,R26_013,22/09/2026,L02 LibraryGreen,Sunny,17,Quiet,Low,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Many,Some,Many,Positive wellbeing,Vey easy,Very calm,Much more connected,Moss,
61,R26_013,22/09/2026,L04 PathFrontiHub,Sunny,16.5,Moderate,Low,Traffic,Human voices,Wind,Other birds,1.0,1.0,Many,Some,Some,Many,Positive wellbeing,Slighly uneasy,Stressful,Less connected,Wind,
62,R26_013,22/09/2026,L05 GreenFrontSportsCentre,Sunny,18,Quiet,Low,Traffic,Human voices,Wind,Other birds,1.0,2.0,Many,Many,Some,Many,Positive wellbeing,Easy,Mostly calm,A little more connected,Wind,
63,R26_013,22/09/2026,L06 HedgingBehindSportsCentre,Sunny,14,Quiet,Low,Traffic,Human voices,Wind,Seagulls,3.0,3.0,,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Seaguls,
64,R26_014,22/09/2026,L04 PathFrontiHub,Sunny,18,Loud,Moderate,Traffic,Human voices,Trees,Wind,0.0,3.0,Many,,Many,,Neutral,Easy,Neutral,Less connected,Trees,
65,R26_014,22/09/2026,L05 GreenFrontSportsCentre,Sunny,18,Moderate,Low,Traffic,Human voices,Seagulls,Trees,0.0,0.0,Many,Some,Some,Some,Positive wellbeing,Neutral,Neutral,Much more connected,Uncut Grass,
69,R26_015,23/09/2026,L02 LibraryGreen,Sunny,18,Moderate,Moderate,Traffic,Human voices,Other birds,Wind,0.0,1.0,Many,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,No change,"Trees, birds, wind sound",gardai
70,R26_015,23/09/2026,L04 PathFrontiHub,Sunny,17,Loud,High,Traffic,Human voices,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Positive wellbeing,Easy,Mostly calm,No change,"Trees, bushes",fumes
71,R26_015,23/09/2026,L05 GreenFrontSportsCentre,Sunny,17,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,3.0,Many,Many,Some,,Positive wellbeing,Easy,Mostly calm,A little more connected,trees,
72,R26_015,23/09/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Human voices,Traffic,Other birds,Trees,0.0,0.0,Many,Many,Many,,Positive wellbeing,Neutral,Very calm,No change,Grass,chair noises in sports hall
73,R26_015,23/09/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Other,Human voices,Wind,Trees,3.0,1.0,Many,Many,Some,Many,Neutral,Easy,Mostly calm,Less connected,"Trees, birds, wind sound",machinery
74,R26_016,23/09/2026,L02 LibraryGreen,Sunny,17,Moderate,High,Traffic,Other,Wind,Insects,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,same,Trees and Grass,
75,R26_016,23/09/2026,L04 PathFrontiHub,Sunny,17,Loud,Moderate,Traffic,Human voices,Wind,Wind,0.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,A little more connected,Trees and Grass,Traffic Volume highest here
76,R26_016,23/09/2026,L05 GreenFrontSportsCentre,Sunny,17,Moderate,Low,Traffic,Human voices,Trees,Insects,2.0,3.0,Many,Many,Some,,Neutral,Easy,Very calm,A little more connected,Trees and Grass,
77,R26_016,23/09/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Human voices,Other,Trees,Other birds,0.0,0.0,Many,Some,Some,,Positive wellbeing,Easy,Very calm,A little more connected,,
78,R26_016,23/09/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Other,Other,Wind,Wind,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,Less connected,,Teleporter and lots of cars (Parking lot)
79,R26_017,23/09/2026,L01 MainEntrance,Partly cloudy,17,Quiet,Low,Traffic,Human voices,Wind,Other birds,1.0,0.0,Many,Many,Some,,Positive wellbeing,Neutral,Mostly calm,No change,grass,a lot of wasp
80,R26_017,23/09/2026,L02 LibraryGreen,Partly cloudy,17,Loud,High,Traffic,Human voices,Wind,Trees,0.0,0.0,Many,Many,Some,,Neutral,Neutral,Neutral,A little more connected,trees,rocks on the floor
81,R26_017,23/09/2026,L07 CarParkNearSportsCentre,Partly cloudy,17,Quiet,Low,Human voices,Service machinery,Wind,Other,1.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees,a telehandler
82,R26_017,23/09/2026,L06 HedgingBehindSportsCentre,Partly cloudy,17,Quiet,Low,Traffic,Service machinery,Insects,Wind,1.0,0.0,Many,Some,Some,,Low wellbeing,Vey easy,Neutral,Less connected,ornamental plants,
83,R26_017,23/09/2026,L04 PathFrontiHub,Partly cloudy,17,Loud,High,Human voices,Human voices,Wind,Trees,1.0,0.0,Many,Many,Some,,Neutral,Neutral,Neutral,Less connected,Trees and Grass,Berries on the bush
84,R26_018,23/09/2026,L05 GreenFrontSportsCentre,Partly cloudy,17,Moderate,Low,Traffic,Human voices,Wind,Trees,0.0,3.0,Many,Many,Some,,Neutral,Neutral,Neutral,A little more connected,Trees,Patio made for sitting and relaxing
85,R26_018,23/09/2026,L06 HedgingBehindSportsCentre,Sunny,16,Quiet,Low,Human voices,Other,Other birds,Trees,1.0,0.0,Many,Many,Many,Some,Neutral,Neutral,Neutral,No change,Spider and Shrubs,
86,R26_018,23/09/2026,L07 CarParkNearSportsCentre,Partly cloudy,16,Moderate,Low,Human voices,Other,Wind,Trees,3.0,1.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Nothing worth noting,Teleporter and lots of cars (Parking lot)
87,R26_018,23/09/2026,L02 LibraryGreen,Partly cloudy,17,Moderate,High,Human voices,Traffic,Other birds,Wind,0.0,0.0,Many,Some,Some,Some,Neutral,Neutral,Neutral,No change,Trees and Grass,Lot of people nd olice station
88,R26_018,23/09/2026,L04 PathFrontiHub,Partly cloudy,17,Moderate,Moderate,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Some,Some,Many,Neutral,Neutral,Neutral,No change,Trees,Traffic Volume highest here
89,R26_019,24/09/2026,L04 PathFrontiHub,Sunny,17,Moderate,High,Traffic,Human voices,Wind,Trees,7.0,6.0,Many,Some,Some,Some,Positive wellbeing,Slighly uneasy,Neutral,A little more connected,Bugs,Lots of smokers/vapers
90,R26_019,25/09/2026,L03 LowerSidePathiHub,Sunny,17,Quiet,Low,Human voices,Traffic,Wind,Trees,1.0,0.0,Many,Many,Many,Some,Positive wellbeing,Easy,Neutral,A little more connected,Lots of weeds,No one around
91,R26_019,26/09/2026,L05 GreenFrontSportsCentre,Sunny,17,Quiet,Low,Traffic,Human voices,Trees,Wind,3.0,0.0,Many,Some,,,Very positive wellbeing,Vey easy,Very calm,Much more connected,Wild ladybug apppeared on me,Ants on my sheet
92,R26_019,27/09/2026,L06 HedgingBehindSportsCentre,Sunny,17,Quiet,Low,Construction,Human voices,Wind,Trees,2.0,2.0,One or two,Some,Some,Some,Neutral,Slighly uneasy,Neutral,Much more connected,"Crabapple tree, apples sour",Lots of webs no spiders
93,R26_019,28/09/2026,L07 CarParkNearSportsCentre,Sunny,17,Quiet,Low,Construction,Service machinery,Other birds,Seagulls,20.0,1.0,One or two,Some,,,Positive wellbeing,Vey easy,Mostly calm,A little more connected,A wild mushroom appeared,Big tele handler with extended Boom
94,R26_020,23/09/2026,L05 GreenFrontSportsCentre,sunny,17,Quiet,Low,Human voices,,Wind,Trees,1.0,0.0,Many,Many,Many,,Positive wellbeing,Easy,Mostly calm,Much more connected,bit shaded area,trash/cloths near the wall area
95,R26_021,24/09/2026,L03 LowerSidePathiHub,sunny,17,Quiet,Low,Human voices,,Wind,,2.0,0.0,Many,Some,Many,Many,Positive wellbeing,Easy,Mostly calm,Much more connected,quiet almost no people arounf,
96,R26_022,25/09/2026,L06 HedgingBehindSportsCentre,sunny,17,Quiet,Low,Human voices,,Wind,,2.0,3.0,One or two,Some,Some,Some,Positive wellbeing,Easy,Mostly calm,A little more connected,small apple tree,very sour apples growing on the tree advised n...
97,R26_023,26/09/2026,L07 CarParkNearSportsCentre,sunny,17,Quiet,Low,Construction,Other,Other birds,Other,25.0,5.0,One or two,Some,Some,,Positive wellbeing,Easy,Mostly calm,Much more connected,clean area,telehandler parked close by eye sore
98,R26_024,27/09/2026,L01 MainEntrance,sunny,17,Moderate,Low,Traffic,Human voices,Wind,Trees,10.0,2.0,Many,Some,,Some,Neutral,Easy,Neutral,Less connected,alot of bugs flying around,

The updated code above works by these steps.
- Removes Rows and Columns with noting in them
- Convert cells containing NaN to empty space (" ")
- Cteate a new list from old list with rows 2-23 sliced out / Because column 0 and 1 contain preinput data
- Saves rows if they have data anywhere in colums 2-23
- Updates original List to only contain the rows and colums with data (Including the " ", only if data is in the row/column)